In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
pd.set_option('display.max_columns',None)

In [3]:
raw_data = pd.read_csv('Credit_default_dataset.csv')
raw_data

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  \
0          1    20000.0    2          2         1   24      2      2     -1   
1          2   120000.0    2          2         2   26     -1      2      0   
2          3    90000.0    2          2         2   34      0      0      0   
3          4    50000.0    2          2         1   37      0      0      0   
4          5    50000.0    1          2         1   57     -1      0     -1   
...      ...        ...  ...        ...       ...  ...    ...    ...    ...   
29995  29996   220000.0    1          3         1   39      0      0      0   
29996  29997   150000.0    1          3         2   43     -1     -1     -1   
29997  29998    30000.0    1          2         2   37      4      3      2   
29998  29999    80000.0    1          3         1   41      1     -1      0   
29999  30000    50000.0    1          2         1   46      0      0      0   

       PAY_4  PAY_5  PAY_6  BILL_AMT1  BILL_AMT2  BILL_AMT3  BILL_AMT4  \
0         -1     -2     -2     3913.0     3102.0      689.0        0.0   
1          0      0      2     2682.0     1725.0     2682.0     3272.0   
2          0      0      0    29239.0    14027.0    13559.0    14331.0   
3          0      0      0    46990.0    48233.0    49291.0    28314.0   
4          0      0      0     8617.0     5670.0    35835.0    20940.0   
...      ...    ...    ...        ...        ...        ...        ...   
29995      0      0      0   188948.0   192815.0   208365.0    88004.0   
29996     -1      0      0     1683.0     1828.0     3502.0     8979.0   
29997     -1      0      0     3565.0     3356.0     2758.0    20878.0   
29998      0      0     -1    -1645.0    78379.0    76304.0    52774.0   
29999      0      0      0    47929.0    48905.0    49764.0    36535.0   

       BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  \
0            0.0        0.0       0.0     689.0       0.0       0.0       0.0   
1         3455.0     3261.0       0.0    1000.0    1000.0    1000.0       0.0   
2        14948.0    15549.0    1518.0    1500.0    1000.0    1000.0    1000.0   
3        28959.0    29547.0    2000.0    2019.0    1200.0    1100.0    1069.0   
4        19146.0    19131.0    2000.0   36681.0   10000.0    9000.0     689.0   
...          ...        ...       ...       ...       ...       ...       ...   
29995    31237.0    15980.0    8500.0   20000.0    5003.0    3047.0    5000.0   
29996     5190.0        0.0    1837.0    3526.0    8998.0     129.0       0.0   
29997    20582.0    19357.0       0.0       0.0   22000.0    4200.0    2000.0   
29998    11855.0    48944.0   85900.0    3409.0    1178.0    1926.0   52964.0   
29999    32428.0    15313.0    2078.0    1800.0    1430.0    1000.0    1000.0   

       PAY_AMT6  default.payment.next.month  
0           0.0                           1  
1        2000.0                           1  
2        5000.0                           0  
3        1000.0                           0  
4         679.0                           0  
...         ...                         ...  
29995    1000.0                           0  
29996       0.0                           0  
29997    3100.0                           1  
29998    1804.0                           1  
29999    1000.0                           1  

[30000 rows x 25 columns]

In [4]:
raw_data.isnull().sum()

ID                            0
LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default.payment.next.month    0
dtype: int64

In [5]:
raw_data['MARRIAGE'].unique()

array([1, 2, 3, 0], dtype=int64)

In [6]:
raw_data['EDUCATION'].unique()

array([2, 1, 3, 5, 4, 6, 0], dtype=int64)

In [7]:
credit_data = raw_data.copy()

In [8]:
credit_data.rename(columns={'PAY_0':'PAY_1'},inplace=True)  ## Renaming column for consistency
credit_data.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  PAY_3  PAY_4  \
0   1    20000.0    2          2         1   24      2      2     -1     -1   
1   2   120000.0    2          2         2   26     -1      2      0      0   
2   3    90000.0    2          2         2   34      0      0      0      0   
3   4    50000.0    2          2         1   37      0      0      0      0   
4   5    50000.0    1          2         1   57     -1      0     -1      0   

   PAY_5  PAY_6  BILL_AMT1  BILL_AMT2  BILL_AMT3  BILL_AMT4  BILL_AMT5  \
0     -2     -2     3913.0     3102.0      689.0        0.0        0.0   
1      0      2     2682.0     1725.0     2682.0     3272.0     3455.0   
2      0      0    29239.0    14027.0    13559.0    14331.0    14948.0   
3      0      0    46990.0    48233.0    49291.0    28314.0    28959.0   
4      0      0     8617.0     5670.0    35835.0    20940.0    19146.0   

   BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0        0.0       0.0     689.0       0.0       0.0       0.0       0.0   
1     3261.0       0.0    1000.0    1000.0    1000.0       0.0    2000.0   
2    15549.0    1518.0    1500.0    1000.0    1000.0    1000.0    5000.0   
3    29547.0    2000.0    2019.0    1200.0    1100.0    1069.0    1000.0   
4    19131.0    2000.0   36681.0   10000.0    9000.0     689.0     679.0   

   default.payment.next.month  
0                           1  
1                           1  
2                           0  
3                           0  
4                           0

In [9]:
credit_data = credit_data.drop(['ID'],axis=1)
credit_data.head()

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  PAY_3  PAY_4  \
0    20000.0    2          2         1   24      2      2     -1     -1   
1   120000.0    2          2         2   26     -1      2      0      0   
2    90000.0    2          2         2   34      0      0      0      0   
3    50000.0    2          2         1   37      0      0      0      0   
4    50000.0    1          2         1   57     -1      0     -1      0   

   PAY_5  PAY_6  BILL_AMT1  BILL_AMT2  BILL_AMT3  BILL_AMT4  BILL_AMT5  \
0     -2     -2     3913.0     3102.0      689.0        0.0        0.0   
1      0      2     2682.0     1725.0     2682.0     3272.0     3455.0   
2      0      0    29239.0    14027.0    13559.0    14331.0    14948.0   
3      0      0    46990.0    48233.0    49291.0    28314.0    28959.0   
4      0      0     8617.0     5670.0    35835.0    20940.0    19146.0   

   BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0        0.0       0.0     689.0       0.0       0.0       0.0       0.0   
1     3261.0       0.0    1000.0    1000.0    1000.0       0.0    2000.0   
2    15549.0    1518.0    1500.0    1000.0    1000.0    1000.0    5000.0   
3    29547.0    2000.0    2019.0    1200.0    1100.0    1069.0    1000.0   
4    19131.0    2000.0   36681.0   10000.0    9000.0     689.0     679.0   

   default.payment.next.month  
0                           1  
1                           1  
2                           0  
3                           0  
4                           0

## Data Preprocessing

In [10]:
credit_data['MARRIAGE'].unique()

array([1, 2, 3, 0], dtype=int64)

In [11]:
credit_data['EDUCATION'].unique()

array([2, 1, 3, 5, 4, 6, 0], dtype=int64)

In [12]:
## Mapping the all the unknown categories into one category
credit_data['MARRIAGE'] = credit_data['MARRIAGE'].map({0:3,1:1,2:2,3:3})
credit_data['EDUCATION'] = credit_data['EDUCATION'].map({0:4,1:1,2:2,3:3,4:4,5:4,6:4})

In [13]:
credit_data['EDUCATION'].unique()

array([2, 1, 3, 4], dtype=int64)

In [14]:
credit_data['MARRIAGE'].unique()

array([1, 2, 3], dtype=int64)

In [15]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [16]:
inputs = credit_data.drop(['default.payment.next.month'],axis=1)
inputs.columns

Index(['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_1', 'PAY_2',
       'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6'],
      dtype='object')

In [17]:
target = credit_data['default.payment.next.month']
target.head()

0    1
1    1
2    0
3    0
4    0
Name: default.payment.next.month, dtype: int64

In [18]:
## Scaling the input 
input_scaled = scaler.fit_transform(inputs)

## Train-Test Split

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train,x_test,y_train,y_test = train_test_split(input_scaled,target,test_size=0.3,random_state=365)

In [21]:
## Hyperparameter Optimization
parameters = {
    "learning_rate"    : [0.05, 0.10, 0.15, 0.20, 0.25, 0.30 ],
    "max_depth"        : [ 3, 4, 5, 6, 8, 10, 12, 15],
    "min_child_weight" : [ 1, 3, 5, 7 ],
    "gamma"            : [ 0.0, 0.1, 0.2 , 0.3, 0.4 ],
    "colsample_bytree" : [ 0.3, 0.4, 0.5 , 0.7 ]
}

In [22]:
from sklearn.model_selection import RandomizedSearchCV,GridSearchCV
import xgboost

In [23]:
classifier = xgboost.XGBClassifier(objective = 'binary:logistic')

In [24]:
random_search = RandomizedSearchCV(classifier,param_distributions=parameters,n_iter=5,scoring='neg_log_loss',error_score=0,n_jobs=-1,cv=5,verbose=3,refit=False)


In [25]:
random_search.fit(x_train,y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits


RandomizedSearchCV(cv=5, error_score=0,
                   estimator=XGBClassifier(base_score=None, booster=None,
                                           colsample_bylevel=None,
                                           colsample_bynode=None,
                                           colsample_bytree=None,
                                           enable_categorical=False, gamma=None,
                                           gpu_id=None, importance_type=None,
                                           interaction_constraints=None,
                                           learning_rate=None,
                                           max_delta_step=None, max_depth=None,
                                           min_child_weight=None, missing=nan,
                                           monoto...
                                           scale_pos_weight=None,
                                           subsample=None, tree_method=None,
                                     

In [26]:
random_search.best_params_

{'min_child_weight': 7,
 'max_depth': 4,
 'learning_rate': 0.15,
 'gamma': 0.4,
 'colsample_bytree': 0.5}

In [36]:
classifier = xgboost.XGBClassifier(colsample_bytree=0.5, gamma=0.4, learning_rate=0.15, max_depth=4,
              min_child_weight=7,eval_metric = 'logloss',use_label_encoder=False)

In [37]:
classifier.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.5,
              enable_categorical=False, eval_metric='logloss', gamma=0.4,
              gpu_id=-1, importance_type=None, interaction_constraints='',
              learning_rate=0.15, max_delta_step=0, max_depth=4,
              min_child_weight=7, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1, predictor='auto',
              random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
              subsample=1, tree_method='exact', use_label_encoder=False,
              validate_parameters=1, verbosity=None)

In [38]:
from sklearn.model_selection import cross_val_score
score = cross_val_score(classifier,x_train,y_train,cv=10)

In [39]:
score

array([0.81666667, 0.81428571, 0.82333333, 0.81809524, 0.83190476,
       0.82619048, 0.81333333, 0.81666667, 0.81      , 0.81      ])

In [40]:
accuracy = round(score.mean()*100,3)
accuracy

81.805

In [41]:
y_pred = classifier.predict(x_test) 

In [42]:
from sklearn.metrics import accuracy_score
accuracy_test = round(accuracy_score(y_test,y_pred)*100,3)

In [43]:
accuracy_test

82.244